[package]
name = "vilbat/statemachine"
version = "0.1.5"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Trove = "sleitnick/trove@0.4.0"
Signal = "sleitnick/signal@1.1.0"
Symbol = "sleitnick/symbol@2.0.0"